# Generated by Django 5.0.6 on 2024-10-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('Kota', 'Kota'), ('Kabupaten', 'Kabupaten')], default='Kota', max_length=10),
        ),
    ]
