# Generated by Django 5.0.6 on 2024-10-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED'), ('CONFIRM', 'CONFIRM'), ('ON_THE_WAY', 'ON THE_WAY'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10),
        ),
    ]
